flags: {}
packages:
- '.'
extra-deps:
- Diff-0.3.4
- StateVar-1.1.0.4
- aeson-0.11.2.0
- ansi-terminal-0.6.2.3
- async-2.1.0
- attoparsec-0.13.0.2
- base-orphans-0.5.4
- bifunctors-5.3
- cmdargs-0.10.14
- comonad-5
- contravariant-1.4
- cpphs-1.20.1
- data-default-0.7.0
- data-default-class-0.1.0
- data-default-instances-base-0.1.0
- data-default-instances-containers-0.0.1
- data-default-instances-dlist-0.0.1
- data-default-instances-old-locale-0.0.1
- distributive-0.5.0.2
- dlist-0.7.1.2
- double-conversion-2.0.1.0
- fail-4.9.0.0
- filemanip-0.3.6.3
- fingertree-0.1.1.0
- ghc-paths-0.1.0.9
- hashable-1.2.4.0
- hscolour-1.24
- intern-0.9.1.4
- liquid-fixpoint-0.3.0.1
- liquidhaskell-0.4.1.1
- mtl-2.2.1
- old-locale-1.0.0.7
- old-time-1.1.0.3
- parsec-3.1.11
- polyparse-1.12
- primitive-0.6.1.0
- safe-0.3.9
- scientific-0.3.4.6
- semigroups-0.18.1
- stm-2.4.4.1
- string-conv-0.1.1
- syb-0.6
- tagged-0.8.4
- text-1.2.2.1
- text-format-0.3.1.1
- transformers-compat-0.5.1.4
- unix-compat-0.4.1.4
- unordered-containers-0.2.7.0
- vector-0.11.0.0
- void-0.7.1
resolver: ghc-7.10.1
